#!/bin/bash
#
# This is the general build process for all linux versions.

# Build it and they will come.
info 'building pianobar'
$make >> $1 2>&1
success 'built pianobar'

# Installing FTW!
info 'installing pianobar'
sudo $make install >> $1 2>&1
success 'installed pianobar'
