#!/bin/bash
#
# This is the general build process for all linux versions.

if test $(which apt-get)
then
  if [[ "Ubuntu" == "$(lsb_release -i | awk '{print $3}')" ]]
  then
    if [[ "12.04" == "$(lsb_release -r | awk '{print $2}')" ]]
    then
      . script/setup.linux/ubuntu.12.04
    fi
  fi
fi

. script/setup.linux/install $output
