#!/bin/bash
#
# This is the general build process for all linux versions.

if test $(which apt-get)
then
  if test ! -z $(lsb_release -i | grep "Ubuntu")
  then
    if [[ "$(lsb_release -r | awk '/Release/ {print $2}')" == "12.04" ]]
    then
      . script/setup.linux/ubuntu.12.04
    fi
  fi
fi

# Build it and they will come.
info 'building pianobar'
$make >> $output
success 'built pianobar'

# Installing FTW!
info 'installing pianobar'
$make install >> $output
success 'installed pianobar'
