#!/bin/bash
#
# Bootstrap pianobar installation.
# Bootstrap concept from github.com/play/play

output=/tmp/pianobar-bootstrap

. script/functions/global $output

if [[ "$OS" == "Darwin" ]]
then
  . script/setup.osx/setup
elif [[ "$OS" == "Linux" ]]
then
  . script/setup.linux/setup
fi
