#!/bin/bash
#
# Update pianobar in one simple script

. script/functions/global /dev/null

# Cleanup
info 'cleaning'
$make clean >> /dev/null
success 'cleaned'

# Get any updates.
info 'updating'
git pull --quiet
success 'updated'

. script/bootstrap
