#!/bin/bash
#
# Update pianobar in one simple script

output=/tmp/pianobar-update

. script/functions/global $output

# Cleanup
info 'cleaning'
$make clean >> $output
success 'cleaned'

# Get any updates.
info 'updating'
git pull >> $output
success 'updated'

if [[ "$OS" == "Darwin" ]]
then
  . script/setup.osx/install $output
elif [[ "$OS" == "Linux" ]]
then
  . script/setup.linux/install $output
fi
