.TH pianobar 1

.SH NAME
pianobar \- console pandora.com music player

.SH SYNOPSIS
.B pianobar

.SH DESCRIPTION
.B pianobar
is a lightweight console music player for the personalized online radio
pandora.com.

.SH FILES
.I $XDG_CONFIG_HOME/pianobar/config
or
.I ~/.config/pianobar/config
.RS
Per-user configuration file. See
.B CONFIGURATION.

.SH CONFIGURATION
The configuration file consists of simple
.B key = value
lines. Each terminated with a newline (\\n) character. Keys and values are both
case sensitive. act_*-keys control 
.B pianobar's
key-bindings.

.TP
.B act_help = ?
Show keybindings.

.TP
.B act_songlove = +
Love currently played song.

.TP
.B act_songban = -
Ban current track. It will not be played again and can only removed using the
pandora.com web interface.

.TP
.B act_stationaddmusic = a
Add more music to current station. You will be asked for a search string. Just
follow the instructions.

.TP
.B act_stationcreate = c
Create new station. You have to enter a search string and select the song or
artist of your choice.

.TP
.B act_stationdelete = d
Delete current station.

.TP
.B act_songexplain = e
Explain why this song is played.

.TP
.B act_stationaddbygenre = g
Add genre station provided by pandora.

.TP
.B act_songinfo = i
Print detailed information about currently played song.

.TP
.B act_songmove = m
Move current song to another station

.TP
.B act_songnext = n
Skip current song.

.TP
.B act_songpause = p
Pause/Continue

.TP
.B act_quit = q
Quit
.B pianobar.

.TP
.B act_stationrename = r
Rename currently played station.

.TP
.B act_stationchange = s
Select another station.

.TP
.B act_songtired = t
Ban song for one month.

.TP
.B act_upcoming = u
Show next songs in playlist.

.TP
.B act_stationselectquickmix = x
Select quickmix stations.

.TP
.B audio_format = {aacplus,mp3}
Select audio format. aacplus is default if both libraries (faad, mad) are
available.

.TP
.B control_proxy = host:port
Non-american users need a proxy to use pandora.com. Only the xmlrpc interface
will use this proxy. The music is streamed directly.

.TP
.B control_proxy_type = {http,socks4,socks4a,socks5}
If you want to use a proxy you need to specify the proxy type you're going to
use. Note that
.B socks5
needs an IP address specified in
.B control_proxy

.TP
.B disable_secure_login = {1,0}
If you have problems when loggin in and you know your control proxy
definitively works try setting this option to
.B 1.
It disables the SSL secured login. Beware!
.I Your password will be sent as plain-text!

.TP
.B lastfm_user = your_username
If you want to send your played song to last.fm set this to your last.fm
username.

.TP
.B lastfm_password = plain_password
A password is needed too if you want to scrobble your played song.

.TP
.B lastfm_scrobble_percent = 50-100
When should a track be submitted to last.fm. Percent value. Don't append
percent sign.

.TP
.B password = plaintext_password
Your pandora.com password. Plain-text.

.TP
.B user = your@user.name
Your pandora.com username.

.SH AUTHOR
Lars-Dominik Braun <PromyLOPh@lavabit.com>
